version: '3'
services:
   db-dev:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
      - wpvoldev1:/var/lib/mysql
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == worker-0]
       restart_policy:
         condition: any

   wordpress-dev:
     image: azcrig001cr001-on.azurecr.io/eit/wp 
     volumes:
       - wpdev1:/var/www/html
     ports:
       - "80:80"
     depends_on:
       - db-dev
     environment:
       WORDPRESS_DB_HOST: db-dev:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == worker-1]
       restart_policy:
         condition: on-failure

volumes:
  wpvoldev1:
    external: true  
  wpdev1:
     external: true 
