version: '3'

services:
   db:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
      - minou:/var/lib/mysql
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == worker]
       restart_policy:
         condition: any

   wordpress:
     image: wp/jenkins-demo:latest
     ports:
       - "80:80"
     depends_on:
       - db
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_DATABASE: wordpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_TABLE_PREFIX: wp_
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == worker]
       restart_policy:
         condition: on-failure

volumes:
  minou:
    external: true 
