version: '3'
services:
   db-prod:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
      - wpvolprod1:/var/lib/mysql
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == worker-1]
       restart_policy:
         condition: any

   wordpress-prod:
     image: azcrig001cr001-on.azurecr.io/eit/wp 
     volumes:
       - wpprod1:/var/www/html
     ports:
       - "8000:80"
     depends_on:
       - db-prod
     environment:
       WORDPRESS_DB_HOST: db-prod:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == worker-0]
       restart_policy:
         condition: on-failure

volumes:
  wpvolprod1:
    external: true 
  wpprod1:
    external: true 
